check_task:
  container:
    dockerfile: ci/Dockerfile
    additional_containers:
      - name: postgres
        image: postgres:11-alpine
        port: 5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      - name: minio
        image: bitnami/minio
        port: 9000
        env:
          MINIO_ACCESS_KEY: wLfYx0GqCl9jOA355XVzqQ
          MINIO_SECRET_KEY: 2Z4g1TrMzCYcQUvwzEHJEI3RKkbPSyE0nqGiWJmVZDM
  hex_script: mix local.hex --force
  rebar_script: mix local.rebar --force
  node_modules_cache:
    folder: file_checker/node_modules
    fingerprint_script: cat file_checker/package-lock.json
    populate_script: sh -c "cd file_checker && npm i"
  mix_deps_cache:
    folder: deps
    fingerprint_script: cat mix.lock
    populate_script: mix deps.get
  build_cache:
    folder: _build
  check_script: mix check
  exdoc_artifacts:
    path: "doc/**/*"
    type: "text/html"
  coverage_artifacts:
    path: "cover/*"
    type: "text/html"

docker_builder:
  name: Docker
  only_if: $CIRRUS_REPO_OWNER == 'moonad' && $CIRRUS_BRANCH == 'master'
  depends_on:
    - check
  env:
    DOCKER_PASSWORD: ENCRYPTED[ed0a2d6d1d1b184a4c424f8485d21a938a92b8aeb607de05a50bea2a0e07eedd5c45f02594d073409c47371a7f0f89cb]
    DOCKER_USERNAME: ENCRYPTED[876aa6e366dbec45c680ed5dd112b009bdcace5dd32599c29aa4a370e9dff0c8456ba57d438fb859863cebff3bbbf0b3]
  build_script: docker build --tag moonad/forall-server:latest .
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: docker push moonad/forall-server:latest