version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgweb:
    image: sosedoff/pgweb:0.11.2
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable'

  swagger_ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    environment:
      API_URL: http://localhost:4000/openapi

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: wLfYx0GqCl9jOA355XVzqQ
      MINIO_SECRET_KEY: 2Z4g1TrMzCYcQUvwzEHJEI3RKkbPSyE0nqGiWJmVZDM
    command: server /data